rotatable: 2
layout: |
    ++++++++++++++D++++++++++++++
    +...........................+
    +...........................+
    +...........................+
    +...........................+
    +...........................+
    +...........................+
    +...........................+
    +...........................+
    +...........................+
    D...........................D
    +...........................+
    +...........................+
    +...........................+
    +...........................+
    +...........................+
    +...........................+
    +...........................+
    +...........................+
    +...........................+
    ++++++++++++++D++++++++++++++